### ISSUE TITLE
Define normalization

### ISSUE THREAD

**Issue by retog** [rdf-ext/rdf-normalize#1]
What do you mean by normalization? making graph lean? all literals in normal form c? Change URIs with "../"?

**Comment by ktk** [comment]
@bergos can surely help more but as this is repo contains JSON-LD stuff my guess would be it's refering to RDF Dataset Normalization as described in this [spec](https://json-ld.github.io/normalization/spec/) from the Credentials W3C community group. Subtitle is "A Standard RDF Dataset Normalization Algorithm".

Also in the spec it says the term "normalization" should be replaced by "canonicalization" to be more clear.

**Comment by bergos** [comment]
Thanks @ktk. You are right. I just copied the required code lines from the JSON-LD library and changed the code to work sync. The term normalization was used everywhere, so I haven't spent time thinking about the term.

**Comment by ktk** [comment]
I wrote that a bit misleading, the term discussion is one of the comments in the spec, it didn't happen in there yet. I would propose to follow the spec in the end and choose the term they use.

**Comment by retog** [comment]
thanks. Adding the link to the README would resolve the issue for me.
